import type { Metadata } from 'next'
import { Merriweather, Open_Sans } from 'next/font/google'
import './globals.css'
import Navbar from './Navbar'

const merriweather = Merriweather({ subsets: ['latin'] , weight: ["300", "400", "700", "900"], variable: "--font-display", display: 'swap'})
const openSans = Open_Sans({subsets: ['latin'], variable: "--font-body", display: 'swap'})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${merriweather.variable} ${openSans.variable}`}>
      <body className="bg-light-900">
        <header>
          <Navbar/>
        </header>
        <main>
          {children}
        </main>
        <footer>

        </footer>
      </body>
    </html>
  )
}
